@server = http://localhost:4004
@auth = Authorization: Basic alice:


### Customers
# @name Customers_GET
GET {{server}}/odata/v4/main/Customers
{{auth}}


### Customers
# @name Customers_POST
POST {{server}}/odata/v4/main/Customers
Content-Type: application/json
{{auth}}

{
  "name": "name-6245001",
  "age": 94
}


### Customers
# @name Customers_PATCH
PATCH {{server}}/odata/v4/main/Customers/6245001e-16d3-425a-9e19-7db6eeb0d954
Content-Type: application/json
{{auth}}

{
  "name": "name-6245001",
  "age": 94
}


### Customers
# @name Customers_DELETE
DELETE {{server}}/odata/v4/main/Customers/6245001e-16d3-425a-9e19-7db6eeb0d954
Content-Type: application/json
{{auth}}
